### ISSUE TITLE
Support RTL

### ISSUE THREAD

**Issue by 3a4or** [acefalobi/android-stepper#13]
Library not support Arabic direction it's layout destroyed like attached photo
![Screenshot_٢٠٢١-٠٢-٠١-١٣-٥١-٤٥-٣٠١_com aceinteract android stepper 1](https://user-images.githubusercontent.com/32014588/106449296-dff14300-6494-11eb-8b9c-0e5bd7dc5b9a.jpg)

**Comment by acefalobi** [comment]
@3a4or this is only for the tab steppers right?

**Comment by mashour10** [comment]
@acefalobi  Yes

**Comment by acefalobi** [comment]
I have fixed this issue in version 0.2.2 now. You should have no issues with RTL support from that version

**Comment by EslamWaheed** [comment]
@acefalobi Issue still exist in version 0.2.2
