### ISSUE TITLE
Remove idea directory from the repository

### ISSUE THREAD

**Issue by mspnr** [acefalobi/android-stepper#18]
Here is a friendly suggestion: 

I did not get why to include `.idea` directory to repository. On every workstation I import the project can be a different setup for formatting, java versions etc. So then I have to track (or be distracted by) unnecessary local changes. There are multiple suggestions on the web, which files should be excluded, most contain multiple files. I find that adding just `.idea/` to `.gitignore` if simple enough and keep the repository clean. 

Please tell me what is the reason of including `.idea` to the repository?

**Comment by acefalobi** [comment]
Ah, that's an oversight on my end. It should have been included in the `.gitignore` like you suggested
