### ISSUE TITLE
How to browse stepper from inside a fragment

### ISSUE THREAD

**Issue by mspnr** [acefalobi/android-stepper#20]
Here is a question regarding your example of using the stepper.

In your example with numbered tabs stepper, the only way to go to next step is by clicking the button in the activity itself:
https://github.com/acefalobi/android-stepper/blob/9859d114536e1a7015beb5fc1b77cefa1fa4955a/app/src/main/java/com/aceinteract/android/stepper/presentation/samples/NumberedTabStepperActivity.kt#L60

I would like to build some buttons for going back and forth in the fragment itself (because some processing logic is related to the steps). 

What would be your advice to trigger jump between steps from inside the fragment?

**Comment by acefalobi** [comment]
An easy way to get this done would be to use a shared viewmodel with an observer.

Something like this in your viewmodel
```kotlin
private val _stepChange = MutableStateFlow(StepChangeType.IDLE)
val stepChange: StateFlow<StepChangeType>get() = _stepChange

fun goToNextStep() {
    _stepChange.value = StepChangeType.NEXT_STEP
}

fun goToPreviousStep() {
    _stepChange.value = StepChangeType.PREVIOUS_STEP
}
```

In your activity, you can then collect the flow.
```kotlin
viewModel.stepChange.onEach {
    when (it.type) {
        StepChangeType.NEXT_STEP -> stepper.goToNextStep()                    
        StepChangeType.PREVIOUS_STEP -> stepper.goToPreviousStep()
    }
}.launchIn(lifecycleScope)

```

StepChange.kt
```kotlin
enum class StepChangeType { IDLE, NEXT_STEP, PREVIOUS_STEP }
```


You could also use LiveData for this.

**Comment by Syizuril** [comment]
I have the same problem, I've used that solution, but instead of continuously observing when there is a change but it only gets called once from the viewmodel, btw I use the button in the fragment instead of the activity, any suggestion ?

**Comment by acefalobi** [comment]
Closing this because it seems it has been answered
