### ISSUE TITLE
onStepChanged dispatched too early

### ISSUE THREAD

**Issue by cesarazuero** [acefalobi/android-stepper#22]
On event onStepChanged I can't get a correct reference to fragment being presented, would be good to wait animation finish and then dispatch the event.

**Comment by acefalobi** [comment]
The `onStepChanged` event is mainly for changes to the host activity/fragment. If you want to make changes to the child fragments, you should do that in the nav controller's `addOnDestinationChangedListener` or in the fragment's `onResume`

**Comment by acefalobi** [comment]
Closing this because it seems it has been answered
