### ISSUE TITLE
Scrolling stepper that automatically centers the current step view

### ISSUE THREAD

**Issue by VincentJoshuaET** [acefalobi/android-stepper#23]
So we can avoid this:

![telegram-cloud-photo-size-5-6258076571193683182-y](https://user-images.githubusercontent.com/19756326/123743564-fbe00000-d8df-11eb-876e-35452aad1454.jpg)

**Comment by acefalobi** [comment]
My solution to this is to just make the stepper view scrollable

**Comment by acefalobi** [comment]
Closing this because it has been fixed in v0.3.0
