### ISSUE TITLE
How to make it horizontally scrollable for multiple menu items like attached screen shot

### ISSUE THREAD

**Issue by kishan-jeeves** [acefalobi/android-stepper#24]
![image](https://user-images.githubusercontent.com/84322875/127731398-baf2c809-88fd-46c7-9eed-35d95e8eefe0.png)

**Comment by acefalobi** [comment]
I'll look into implementing this

**Comment by acefalobi** [comment]
Closing this issue now because it has been fixed in v0.3.0
