### ISSUE TITLE
Could not find com.github.acefalobi:android-stepper:0.3.0

### ISSUE THREAD

**Issue by ashotterekyanlmc** [acefalobi/android-stepper#27]
I have this problem. sync gradle finished good, but compile with this exception. 
Does anyone have such a problem? Or is it mine alone?

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':app:checkDebugAarMetadata'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find com.github.acefalobi:android-stepper:0.3.0.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/github/acefalobi/android-stepper/0.3.0/android-stepper-0.3.0.pom
       - https://jcenter.bintray.com/com/github/acefalobi/android-stepper/0.3.0/android-stepper-0.3.0.pom
       - https://jitpack.io/com/github/acefalobi/android-stepper/0.3.0/android-stepper-0.3.0.pom
     Required by:
         project :app

Sorry, problems with my android studios

**Comment by EslamWaheed** [comment]
@ashotterekyanlmc How did you fix this? I have the same issue
