### ISSUE TITLE
Fragments Not Showing

### ISSUE THREAD

**Issue by chaneylc** [acefalobi/android-stepper#32]
Thanks for starting this cool project, although I'm having trouble getting it to work correctly.

I've created a sample project that follows your guide here: [Project Link](https://github.com/chaneylc/StepperDemo)

For some reason the individual fragment steps don't show, only the stepper view.

![image](https://user-images.githubusercontent.com/5421632/151628871-85504d18-462a-42c2-b55d-fc29d795f704.png)

In the sample project each step has a single text view, that shows one, two and three respectively for each step. As you can see those are not visible.

**Comment by acefalobi** [comment]
Are you sure this is set up correctly? Particularly the nav graph destinations and menu item IDs

**Comment by chaneylc** [comment]
Yes I followed your guide completely. Apparently I was inflating the fragment incorrectly, works now.
