### ISSUE TITLE
How I can change the stepper color when it is completed

### ISSUE THREAD

**Issue by shadab-saif** [acefalobi/android-stepper#35]
I want to change the color of widget when the step is competed, How I can achieve it.

**Comment by acefalobi** [comment]
You can programmatically change the `stepperView.widgetColor` to the new color in the `StepperNavListener.onCompleted()`  overrien method.

**Comment by shadab-saif** [comment]
> You can programmatically change the `stepperView,widgetColor` to the new color in the `StepperNavListener.onCompleted()` overrien method.


lateinit var stepper: StepperNavigationView
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_registration)

        val navHostFragment =
            supportFragmentManager.findFragmentById(R.id.frame_stepper) as NavHostFragment
        val navController = navHostFragment.navController

        val stepper = findViewById<StepperNavigationView>(R.id.stepper)
        stepper.setupWithNavController(navController)

    }

    override fun onCompleted() {
        stepper.widgetColor = R.color.purple_200
    }

    override fun onStepChanged(step: Int) {
        TODO("Not yet implemented")
    }



here is my code but it is not working

**Comment by acefalobi** [comment]
`stepperView.widgetColor` takes in a `ColorInt` and not a `ColorRes`. You'll need to use `context.getColor(R.color.purple_200)` or `ContextCompat.getColor(context, R.color.purple_200)` instead

**Comment by shadab-saif** [comment]
> `stepperView.widgetColor` takes in a `ColorInt` and not a `ColorRes`. You'll need to use `context.getColor(R.color.purple_200)` or `ContextCompat.getColor(context, R.color.purple_200)` instead

stepper.widgetColor = ContextCompat.getColor(applicationContext, R.color.purple_200)  (not working)

**Comment by acefalobi** [comment]
Just to confirm, do you want to do this when it's completed or when it gets to the last step.

Because, if it is the latter, you need to put the widget color change in the `onStepChanged()` function.

e.g

```kotlin
override fun onStepChanged(step: Int) {
    if (step == noOfSteps) stepper.widgetColor = ContextCompat.getColor(applicationContext, R.color.purple_200)
}
```

**Comment by shadab-saif** [comment]
These both override function are not even call I have used toast message just to check these function are working or not, and I don't even see the toast.

**Comment by acefalobi** [comment]
Have you connected the listener to the `stepperView` with `stepperView.stepperNavListener = this`

**Comment by shadab-saif** [comment]
I have not connected the listener but now it is working when connected the listener, But it does not give me what I want, I want only completed widget step color change but it will change the complete stepper color.

**Comment by acefalobi** [comment]
Sorry @shadab-saif, unfortunately, the library doesn't include this functionality. But you can always fork the project and add this,
