### ISSUE TITLE
Auto Scroll when goToNextStep() or goToPreviousStep() executed.

### ISSUE THREAD

**Issue by sherwin14** [acefalobi/android-stepper#43]
Hi @acefalobi , I just want to ask if there's a way how to auto center the current step after goToNextStep() or goToPreviousStep() click.

**Comment by acefalobi** [comment]
I'm assuming this is for the tab steppers. That feature doesn't currently exist.

If you need to do that, you would need to fork this repo and add the functionality in the `updateUI` method for `TabStepperMenu.kt` or `TabNumberedStepperMenu.kt` depending on which stepper type you want to customize.

**Comment by sherwin14** [comment]
> I'm assuming this is for the tab steppers. That feature doesn't currently exist.
> 
> If you need to do that, you would need to fork this repo and add the functionality in the `updateUI` method for `TabStepperMenu.kt` or `TabNumberedStepperMenu.kt` depending on which stepper type you want to customize.

Hi @acefalobi Yes I'm using Tab Steppers. Btw I have successfully achieved the features without forking the repo..

What I did is: Inside of OnStepChange(step: Int).

```
override fun onStepChanged(step: Int) {

        val menu = binding.stepper[0] as TabStepperMenu
        val item = menu.getItem(step) as TabStepperMenuItem

        if (binding.stepper.currentStep == 0)
            binding.buttonPrevious.visibility = View.GONE else
            binding.buttonPrevious.visibility = View.VISIBLE

        binding.stepper.postDelayed({
            binding.stepper.smoothScrollTo(item.labelView.left, 0)
        }, 100L)
    }
```

this will also working when you click previous and next button.
