### ISSUE TITLE
APIs lower than 28

### ISSUE THREAD

**Issue by SkyfaceD** [acefalobi/android-stepper#8]
Currently library draws steps correctly only on 28, 29 and 30 APIs. This is bug or library doesn't provide support for lower APIs?

**Screenshots from real devices:**

Tab Stepper on Huawei P10 lite
![Huawei P10 lite](https://user-images.githubusercontent.com/22749309/101019101-a97f7080-3596-11eb-81f9-7d23449c896b.png)

Tab Stepper on ZUK Z2
![ZUK Z2](https://user-images.githubusercontent.com/22749309/101018517-d1ba9f80-3595-11eb-992a-dd02e6be36ed.png)

**Tested on real device:**
- Doesn't work
  - API 26 (8.0), Huawei P10 lite
- Work perfectly
  - API 29 (10.0), Galaxy A70
  - API 29 (10.0), ZUK Z2

**Tested on emulators:**
- Doesn't work
  - API 24
  - API 27
- Work perfectly
  - API 28
  - API 29
  - API 30

**Steps to reproduce**
1. Download [sample](https://github.com/acefalobi/android-stepper/tree/master/app) app
2. Run debug version

**Comment by acefalobi** [comment]
@SkyfaceD it must be a bug. i'll look into it.

**Comment by acefalobi** [comment]
@SkyfaceD does this bug only occur with the tab stepper type?

**Comment by SkyfaceD** [comment]
@acefalobi nope, for all stepper types.

Screens from Huawei P10 lite
**Tab stepper:**
![image](https://user-images.githubusercontent.com/22749309/101237175-dfd8ff00-3700-11eb-9da4-d0e70eab052c.png)

**Numbered tab stepper:**
![image](https://user-images.githubusercontent.com/22749309/101237185-f2ebcf00-3700-11eb-8baf-acb49f5d2e81.png)

**Progress stepper:**
![image](https://user-images.githubusercontent.com/22749309/101237193-f7b08300-3700-11eb-8ec0-872d9a730a85.png)

**Fleets stepper:**
![image](https://user-images.githubusercontent.com/22749309/101237199-0b5be980-3701-11eb-8a0f-0bf615d9a342.png)

**Comment by acefalobi** [comment]
@SkyfaceD if you can, please send me the screenshot of the other types

**Comment by SkyfaceD** [comment]
> @SkyfaceD if you can, please send me the screenshot of the other types

Check editted comment.

**Comment by arthurndossi** [comment]
> @SkyfaceD it must be a bug. i'll look into it.

Hi, did you look into this?

**Comment by arthurndossi** [comment]
I solved this issue by creating a refs.xml in res -> values with content
```
<?xml version="1.0" encoding="utf-8"?>
<resources xmlns:tools="http://schemas.android.com/tools">
    <item name="stepper_progress" type="layout" tools:override="true">@layout/new_stepper_progress</item>
</resources>
```
... and created a new layout file new_stepper_progress same as stepper_progress except for one addition in cardview
app:cardElevation="0dp"

like this...

```
<?xml version="1.0" encoding="utf-8"?>
<androidx.cardview.widget.CardView xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:elevation="0dp"
    android:layout_width="0dp"
    tools:layout_width="match_parent"
    android:layout_height="3dp"
    app:cardElevation="0dp"
    app:cardCornerRadius="100dp">

    <ProgressBar
        android:id="@+id/progress_stepper"
        style="@style/Widget.AppCompat.ProgressBar.Horizontal"
        android:layout_width="match_parent"
        android:layout_height="3dp"
        android:layout_gravity="center"
        android:indeterminate="false"
        android:max="100"
        tools:progress="50"
        tools:progressTint="@color/color_stepper_default" />

</androidx.cardview.widget.CardView>
```

**Comment by acefalobi** [comment]
Thanks for this @arthurndossi.

I'll create an alternate layout for API <28 removing the elevation till I figure out how to fix this.

**Comment by arthurndossi** [comment]
Just add this line 
```
app:cardElevation="0dp"
```
for CardView in each layout in android-stepper/stepper/src/main/res/layout/.
No need to create another layout.

**Comment by acefalobi** [comment]
the card elevation is what gives it the nice subtle shadow.

**Comment by acefalobi** [comment]
@SkyfaceD and @arthurndossi can you try with the [feature/stepper-type](https://github.com/acefalobi/android-stepper/tree/feature/stepper-type) branch and see if it works for you.

**Comment by arthurndossi** [comment]
Alright👍

**Comment by ashotterekyanlmc** [comment]
@acefalobi Hello. Numbers are not displayed on android 6 and 7. the problem remains :(

**Comment by mspnr** [comment]
Missing numbers can be fixed by changing `cardCornerRadius` to 10dp here:

https://github.com/acefalobi/android-stepper/blob/b7c39b496ef673fbd2765f8a70ba99327c578f5d/stepper/src/main/res/layout/stepper_tab_item_number_icon.xml#L9

**Comment by acefalobi** [comment]
closing this cos it seems to have been fixed
