### ISSUE TITLE
Java support

### ISSUE THREAD

**Issue by srserx** [acefalobi/android-stepper#9]
The following code seems to be only supported by Kotlin:

<img width="905" alt="Captura de pantalla 2020-12-04 a las 12 26 33" src="https://user-images.githubusercontent.com/21047502/101158446-05e09f80-362c-11eb-9675-e8b6b93f9221.png">

as the _setupWithNavController_ call in java asks for a second parameter, which must be an AnimBuilder. But AnimBuilder seems not to be available for Java: 

<img width="946" alt="Captura de pantalla 2020-12-04 a las 12 29 05" src="https://user-images.githubusercontent.com/21047502/101158635-52c47600-362c-11eb-87a6-e9d3b303da78.png">

Is there any workaround in order to make it work with Java as well?

Thanks a lot in advance!

**Comment by srserx** [comment]
Found out we can use both Java and Kotlin in the same project :-)

**Comment by acefalobi** [comment]
Hi @srserx,

The AnimBuilder class is written in Kotlin, but it is still interoperable with Java so yes you can use the function like this:

```java
StepperNavigationView stepper = findViewById(R.id.stepper);
NavController navController = ActivityKt.findNavController(this, R.id.frame_stepper);
stepper.setupWithNavController(
        navController,
        builder -> {
            builder.setEnter(android.R.anim.fade_in);
            builder.setExit(android.R.anim.fade_out);
            builder.setPopEnter(android.R.anim.fade_in);
            builder.setPopExit(android.R.anim.fade_out);
            return Unit.INSTANCE;
        }
);
```

I will add a `@JvmOverloads` annotation to the `setupWithNavController` function so you can use it with the default `AnimBuilder` like:

```java
stepper.setupWithNavController(navController);
```
